package main;

public class KineticPieces {

	public static String tablehead(String onto1, String onto2) {
		return "<!DOCTYPE html>\n"
				+ "<html>\n"
				+ "<title>OntoVis - Table mode</title>\n"
				+ "<body>\n"
				+ "<div id=\"container\">\n"
				+ "<div id=\"header\" style=\"background-color:#8AA8E6;\">\n"
				+ "<h1 style=\"margin-top:0;margin-bottom:0;\">\n"
				+ "<img src=\"./logoOntoVis3.png\" alt=\"OntoVis\">Table Mode</h1>\n"
				+ "</div>\n"
				+ "<div id=\"menu\" style=\"background-color:#8AB8E6;height:100%;width:120px;float:left;\">\n"
				+ "<p><input type=\"text\" id=\"baremo\" size=\"4\" maxLength=\"6\" value=\"0.0\"></p>\n"
				+ "<p>Show<br>"
				+ "<input type=\"checkbox\" id=\"=\">="
				+ "<input type=\"checkbox\" id=\"<\"><"
				+ "<input type=\"checkbox\" id=\">\">><br>"
				+ "<input type=\"checkbox\" id=\"others\">Others\n"
				+ "<br><br><input type=\"checkbox\" id=\"classchk\">Classes"
				+ "<br><input type=\"checkbox\" id=\"propchk\">Properties"
				+ "<br><input type=\"checkbox\" id=\"datachk\">Datatypes"
				+ "<p><button onclick=\"filtro()\" id=\"botfil\" type=\"button\">Filter</button></p>\n"
				+ "<p><input type=\"checkbox\" id=\"botedi\" onclick=\"editor()\">Edit mode</p>\n"
				+ "<input type=\"radio\" name=\"rel\" id=\"rd=\" value=\"=\" disabled=\"true\" checked=\"true\">="
				+ "<input type=\"radio\" name=\"rel\" id=\"rd<\" value=\"<\" disabled=\"true\"><"
				+ "<input type=\"radio\" name=\"rel\" id=\"rd>\" value=\">\" disabled=\"true\">>\n" +
				  "<p><input type=\"text\" id=\"valorin\" size=\"4\" maxLength=\"6\" value=\"0.0\" disabled=\"true\"></p>" +
				  "<p><button onclick=\"fijarCambios()\" type=\"button\">Accept</button></p>\n" + 
				  "<p><button onclick=\"hacerCopia()\" type=\"button\">Save Copy</button></p>\n"
				//+ "<p><button onclick=\"location.href='/ontovis/main.jsp'\" type=\"button\">Back</button></p>\n"
				+ "<p><button onclick=\"history.back()\" type=\"button\">Back</button></p>\n"
				+ "Scroll using<br>"
				+ "Up/Down &<br>"
				+ "Left/Right keys"
				+ "</div>\n"
				+ "<div id=\"content\" style=float:left;\">"
				//+ "<div id=\"content\" style=\"height:"
				//+ height
				//+ "px;width:"+(width-120)+"px;float:left;\">\n"
				+ "</div>\n"
				+ "<div id=\"footer\" style=\"background-color:#8AB8E6;clear:both;text-align:center;\">\n"
				+ "© Victor Albir 2012-2013</div>\n"
				+ "</div>\n"
				//+ "<script src=\"kinetic-v4.0.5.min.js\"></script>"
				+ "<script src=\"kinetic-v4.3.3.min.js\"></script>\n"
				+ "<script>\n"
				+ "function filtro(){\n"
				+ "stage.reset();\n"
				+ "umbral=parseFloat(document.getElementById(\"baremo\").value);\n"
				+ "if (document.getElementById(\"propchk\").checked && propchkbefore == 1){\n"
				+ "    offsetR = rowsClassIDs.length;\n"
				+ "    offsetC = colsClassIDs.length;\n"
				+ "    offsetPC = 0;\n"
				+ "    offsetPR = 0;\n"
				+ "    offsetDC = 0;\n"
				+ "    offsetDR = 0;\n"
				+ "    propchkbefore = 0;\n"
				+ "}\n"
				+ "if (document.getElementById(\"classchk\").checked && classchkbefore == 1){\n"
				+ "    classchkbefore = 0;\n"
				+ "    offsetR = 0;\n"
				+ "    offsetC = 0;\n"
				+ "    offsetPC = 0;\n"
				+ "    offsetPR = 0;\n"
				+ "    offsetDC = 0;\n"
				+ "    offsetDR = 0;\n"
				+ "}\n"
				+ "if (!document.getElementById(\"propchk\").checked && propchkbefore == 0){\n"
				+ "    if (classchkbefore == 1){\n"
				+ "       offsetR = rowsClassIDs.length;\n"
				+ "       offsetC = colsClassIDs.length;\n"
				+ "       if (rowsDataIDs.length < nottoofar){\n"
				+ "           offsetPR = rowsPropIDs.length-nottoofar;\n"
				+ "       } else {\n"
				+ "           offsetPR = rowsPropIDs.length;\n"
				+ "       }\n"
				+ "       offsetPC = colsPropIDs.length;\n"
				+ "    } else {\n"
				+ "       offsetR = 0;\n"
				+ "       offsetC = 0;\n"
				+ "    }\n"
				+ "    offsetDC = 0;\n"
				+ "    offsetDR = 0;\n"
				+ "    propchkbefore = 1;\n"
				+ "}\n"
				+ "if (!document.getElementById(\"classchk\").checked && classchkbefore == 0){\n"
				+ "    if (propchkbefore == 1){\n"
				+ "       offsetPC = colsPropIDs.length;\n"
				+ "       if (rowsDataIDs.length < nottoofar){\n"
				+ "           offsetPR = rowsPropIDs.length-nottoofar;\n"
				+ "       } else {\n"
				+ "           offsetPR = rowsPropIDs.length;\n"
				+ "       }\n"
				+ "    } else {\n"
				+ "       offsetPC = 0;\n"
				+ "       offsetPR = 0;\n"
				+ "    }\n"
				+ "    offsetR = rowsClassIDs.length;\n"
				+ "    offsetC = colsClassIDs.length;\n"
				+ "    offsetDC = 0;\n"
				+ "    offsetDR = 0;\n"
				+ "    classchkbefore = 1;\n"
				+ "}\n"
				+ "dibujo(stage);\n"
				+ "}\n"
				+ "function editor(){\n"
				+ "    if (modo == 0){\n"
				+ "    document.getElementById(\"rd=\").disabled = false;\n"
				+ "    document.getElementById(\"rd<\").disabled = false;\n"
				+ "    document.getElementById(\"rd>\").disabled = false;\n"
				+ "    document.getElementById(\"valorin\").disabled = false;\n"
				+ "    document.getElementById(\"=\").checked = true;\n"
				+ "    document.getElementById(\"<\").checked = true;\n"
				+ "    document.getElementById(\">\").checked = true;\n"
				+ "    document.getElementById(\"others\").checked = true;\n"
			    + "    document.getElementById(\"=\").disabled = true;\n"
				+ "    document.getElementById(\"<\").disabled = true;\n"
				+ "    document.getElementById(\">\").disabled = true;\n"
				+ "    document.getElementById(\"others\").disabled = true;\n"
				+ "    document.getElementById(\"baremo\").disabled = true;\n"
				+ "    document.getElementById(\"botfil\").disabled = true;\n"
				+ "    document.getElementById(\"classchk\").checked = true;\n"
				+ "    document.getElementById(\"propchk\").checked = true;\n"
				+ "    document.getElementById(\"datachk\").checked = true;\n"
				+ "    document.getElementById(\"classchk\").disabled = true;\n"
				+ "    document.getElementById(\"propchk\").disabled = true;\n"
				+ "    document.getElementById(\"datachk\").disabled = true;\n"
				+ "    umbral = 0.0;\n"
				+ "    modo = 1;\n"
				+ "    stage.reset();\n"
				+ "    dibujo(stage);\n"
				+ "    } else {\n"
				+ "    document.getElementById(\"rd=\").disabled = true;\n"
				+ "    document.getElementById(\"rd<\").disabled = true;\n"
				+ "    document.getElementById(\"rd>\").disabled = true;\n"
				+ "    document.getElementById(\"valorin\").disabled = true;\n"
				+ "    document.getElementById(\"=\").disabled = false;\n"
				+ "    document.getElementById(\"<\").disabled = false;\n"
				+ "    document.getElementById(\">\").disabled = false;\n"
				+ "    document.getElementById(\"others\").disabled = false;\n"
				+ "    document.getElementById(\"baremo\").disabled = false;\n"
				+ "    document.getElementById(\"botfil\").disabled = false;\n"
				+ "    document.getElementById(\"classchk\").disabled = false;\n"
				+ "    document.getElementById(\"propchk\").disabled = false;\n"
				+ "    document.getElementById(\"datachk\").disabled = false;\n"
				+ "    modo = 0;\n"
				+ "stage.reset();\n"
				+ "    inicializar();\n"
				//+ "stage = reset(stage);\n"
				/*+ "    stage.remove();\n"
				+ "    stage = new Kinetic.Stage({\n"
				+ "        container: \"content\",\n"
				+ "        width: stwidth,\n"
				+ "        height: stheight,\n"
				+ "    });\n"*/
		        + "dibujo(stage);\n"
				+ "    }\n"
				+ "}\n"
				+ "function fijarCambios(){\n"
				+ "    if (modo == 1){\n"
				+ "    document.getElementById(\"rd=\").disabled = true;\n"
				+ "    document.getElementById(\"rd<\").disabled = true;\n"
				+ "    document.getElementById(\"rd>\").disabled = true;\n"
				+ "    document.getElementById(\"valorin\").disabled = true;\n"
				+ "    document.getElementById(\"=\").disabled = false;\n"
				+ "    document.getElementById(\"<\").disabled = false;\n"
				+ "    document.getElementById(\">\").disabled = false;\n"
				+ "    document.getElementById(\"others\").disabled = false;\n"
				+ "    document.getElementById(\"baremo\").disabled = false;\n"
				+ "    document.getElementById(\"botfil\").disabled = false;\n"
				+ "    document.getElementById(\"botedi\").checked = false;\n"
				+ "    modo = 0;\n"
				+ "stage.reset();\n"
				/*+ "    stage.remove();\n"
				+ "    stage = new Kinetic.Stage({\n"
				+ "        container: \"content\",\n"
				+ "        width: stwidth,\n"
				+ "        height: stheight,\n"
				+ "    });\n"*/
		        + "dibujo(stage);\n"
				+ "    }\n"
				+ "}\n"
				+ "function hacerCopia(){\n"
				// TODO: funcion que avisa al servidor para construir el fichero
				// de ontologia modificado
				+ "var xmlhttp;\n"
				+ "if (window.XMLHttpRequest)\n"
				+ "  {// code for IE7+, Firefox, Chrome, Opera, Safari\n"
				+ "  xmlhttp=new XMLHttpRequest();\n"
				+ "  }\n"
				+ "else\n"
				+ "  {// code for IE6, IE5\n"
				+ "  xmlhttp=new ActiveXObject(\"Microsoft.XMLHTTP\");\n"
				+ "  }\n"
				+ "xmlhttp.open(\"POST\",\"fileCopy.jsp\",false);\n"
				//+ "xmlhttp.send(\"chng=\"+cambios.join())\n;"
				+ "xmlhttp.setRequestHeader(\"Content-type\",\"application/x-www-form-urlencoded\");\n"
				//+ "xmlhttp.send(\"q=\"+rowsClassIDs+\"@\"+rowsPropIDs+\"@\"+rowsDataIDs+\"@\"+colsClassIDs+\"@\"+colsPropIDs+\"@\"+colsDataIDs+\"@\"+colsValues+\"@"+onto1+"@"+onto2+"\");\n"
			    +"xmlhttp.send(\"q=\"+rowsClassIDs.concat(rowsPropIDs.concat(rowsDataIDs))+\"@\"+colsClassIDs.concat(colsPropIDs.concat(colsDataIDs))+\"@\"+colsValues+\"@"+onto1+"@"+onto2+"\");\n" 
				+ "location.href='/ontovis/alignment.rdf'"
				+ "}\n"
				+ "document.getElementById(\"=\").checked=true;\n"
				+ "document.getElementById(\"<\").checked=true;\n"
				+ "document.getElementById(\">\").checked=true;\n"
				+ "document.getElementById(\"others\").checked=true;\n"
				+ "document.getElementById(\"classchk\").checked=true;\n"
				+ "document.getElementById(\"propchk\").checked=true;\n"
				+ "document.getElementById(\"datachk\").checked=true;\n"
				+ "var classchkbefore = 0;\n"
				+ "var propchkbefore = 0;\n"
				+ "var datachkbefore = 0;\n"
				+ "var umbral = 0;\n"
				+ "var modo = 0;\n"
				+ "var w=window,d=document,e=d.documentElement,g=d.getElementsByTagName('body')[0],x=w.innerWidth||e.clientWidth||g.clientWidth,y=w.innerHeight||e.clientHeight||g.clientHeight;"
			    //+ "var stwidth = "+(width-120)+";\n"
				//+ "var stheight = "+ height+ ";\n"
				+ "    var stage = new Kinetic.Stage({\n"
				+ "        container: \"content\",\n"
				+ "        width: x - 155,\n"
				+ "        height: y - 99,\n"
				+ "    });\n"
				+ "var offsetC = 0;\n"
				+ "var offsetR = 0;\n"
				+ "var offsetPC = 0;\n"
				+ "var offsetPR = 0;\n"
				+ "var offsetDC = 0;\n"
				+ "var offsetDR = 0;\n"
				+ "var nottoofar = parseInt((stage.getHeight()-25) / 30);\n"
				+ "document.onkeydown = function(evt){\n"
				+ "    evt = evt || window.event;\n"
				+ "    switch (evt.keyCode) {\n"
				+ "        case 37:\n"
				+ "            leftArrow();\n"
				+ "            break;\n"
				+ "        case 38:\n"
				+ "            upArrow();\n"
				+ "            break;\n"
				+ "        case 39:\n"
				+ "            rightArrow();\n"
				+ "            break;\n"
				+ "        case 40:\n"
				+ "            downArrow();\n"
				+ "            break;\n"
				+ "    }\n"
				+ "};\n"
				+ "function upArrow(){\n"
				+ "    if (document.getElementById(\"classchk\").checked\n"
				+ "        && offsetR > 0 && offsetPR == 0){\n"
				+ "       offsetR = offsetR - 1;\n"
				//+ "       lineas.removeChildren();\n"
				+ "       stage.reset();\n"
				+ "       dibujo(stage);\n"
				+ "        return;\n"
				+ "    }\n"
				+ "    if (offsetPR > 0 && offsetDR == 0){\n"
				+ "       offsetPR = offsetPR - 1;\n"
				//+ "       lineas.removeChildren();\n"
				+ "       stage.reset();\n"
				+ "       dibujo(stage);\n"
				+ "        return;\n"
				+ "    }\n"
				+ "    if (offsetDR > 0){\n"
				+ "       offsetDR = offsetDR - 1;\n"
				//+ "       lineas.removeChildren();\n"
				+ "       stage.reset();\n"
				+ "       dibujo(stage);\n"
				+ "        return;\n"
				+ "    }\n"
				+ "}"
				+ "function downArrow(){\n"
				+ "    if (document.getElementById(\"datachk\").checked" +
				  "        && ((document.getElementById(\"propchk\").checked && offsetPR == rowsPropIDs.length) || !document.getElementById(\"propchk\").checked)" +
				  "            && ((document.getElementById(\"classchk\").checked && offsetR == rowsClassIDs.length) || !document.getElementById(\"classchk\").checked)" +
				  "            && offsetDR < rowsDataIDs.length-nottoofar){\n"
				+ "        offsetDR = offsetDR + 1;\n"
				+ "        stage.reset();\n"
				+ "        dibujo(stage);\n"
				+ "        return;\n"
				+ "    }\n"
				+ "    if (document.getElementById(\"propchk\").checked" +
				  "        && ((document.getElementById(\"classchk\").checked && offsetR == rowsClassIDs.length) || !(document.getElementById(\"classchk\").checked))" +
				  "        && ((document.getElementById(\"datachk\").checked && (rowsPropIDs.length - offsetPR + rowsDataIDs.length) > nottoofar && offsetPR < rowsPropIDs.length)" +
				  "            || offsetPR < rowsPropIDs.length-nottoofar)){\n"
				+ "        offsetPR = offsetPR + 1;\n"
				+ "        stage.reset();\n"
				+ "        dibujo(stage);\n"
				+ "        return;\n"
				+ "    }\n"
				+ "    if (document.getElementById(\"classchk\").checked &&" +
				  "        ((document.getElementById(\"propchk\").checked && rowsClassIDs.length - offsetR + rowsPropIDs.length - offsetPR > nottoofar)" +
				  "        || (!document.getElementById(\"propchk\").checked && document.getElementById(\"datachk\").checked && (rowsClassIDs.length - offsetR + rowsDataIDs.length > nottoofar+1) && offsetR < rowsClassIDs.length)" +
				  "        || offsetR < rowsClassIDs.length-nottoofar)){\n"
				+ "        offsetR = offsetR + 1;\n"
				+ "        stage.reset();\n"
				+ "        dibujo(stage);\n"
				+ "        return;\n"
				+ "    }\n"
				+ "}\n"
                + "function leftArrow(){\n"
                + "    if (document.getElementById(\"classchk\").checked\n"
				+ "       && offsetC > 0 && offsetPC == 0){\n"
				+ "       offsetC = offsetC - 1;\n"
				//+ "       lineas.removeChildren();\n"
				+ "       stage.reset();\n"
				+ "       dibujo(stage);\n"
				+ "        return;\n"
				+ "    }\n"
				+ "    if (offsetPC > 0 && offsetDC == 0){\n"
				+ "       offsetPC = offsetPC - 1;\n"
				//+ "       lineas.removeChildren();\n"
				+ "       stage.reset();\n"
				+ "       dibujo(stage);\n"
				+ "        return;\n"
				+ "    }\n"
				+ "    if (offsetDC > 0){\n"
				+ "       offsetDC = offsetDC - 1;\n"
				//+ "       lineas.removeChildren();\n"
				+ "       stage.reset();\n"
				+ "       dibujo(stage);\n"
				+ "        return;\n"
				+ "    }\n"
				+ "}"
                + "function rightArrow(){\n"
                + "    if (document.getElementById(\"datachk\").checked" +
                  "        && ((document.getElementById(\"propchk\").checked && offsetPC == colsPropIDs.length) || !document.getElementById(\"propchk\").checked)" +
                  "        && ((document.getElementById(\"classchk\").checked && offsetC == colsClassIDs.length) || !document.getElementById(\"classchk\").checked)" +
                  "        && offsetDC < colsDataIDs.length){\n"
				+ "        offsetDC = offsetDC + 1;\n"
				+ "        stage.reset();\n"
				+ "        dibujo(stage);\n"
				+ "        return;\n"
				+ "    }\n"
				+ "    if (document.getElementById(\"propchk\").checked" +
				  "        && ((document.getElementById(\"classchk\").checked && offsetC == colsClassIDs.length)" +
				  "        || !document.getElementById(\"classchk\").checked)" +
				  "        && (!document.getElementById(\"datachk\").checked" +
				  "        || document.getElementById(\"datachk\").checked && (colsPropIDs.length - offsetPC + colsDataIDs.length) >= nottoofar && offsetPC < colsPropIDs.length" +
				  "        || offsetPC < colsPropIDs.length)){\n"
				+ "        offsetPC = offsetPC + 1;\n"
				+ "        stage.reset();\n"
				+ "        dibujo(stage);\n"
				+ "        return;\n"
				+ "    }\n"
				+ "    if (document.getElementById(\"classchk\").checked &&" +
				  "        ((document.getElementById(\"propchk\").checked && colsClassIDs.length - offsetR + colsPropIDs.length >= nottoofar)||" +
				  "        (document.getElementById(\"datachk\").checked && (colsClassIDs.length - offsetR + colsDataIDs.length >= nottoofar) && offsetC < colsClassIDs.length)" +
				  "        || offsetC < colsClassIDs.length)){\n"
				+ "        offsetC = offsetC + 1;\n"
				+ "        stage.reset();\n"
				+ "        dibujo(stage);\n"
				+ "        return;\n"
				+ "    }\n"
				+ "}\n"
				+ "var onto1 = \""+onto1+"\";\n"
				+ "var onto2 = \""+onto2+"\";\n"
				/*+ "function reset(stg) {\n"
				+ "    stg.destroy();\n"
				+ "    var newstage = new Kinetic.Stage({\n"
				+ "        container: \"content\",\n"
				+ "        width: stwidth,\n"
				+ "        height: stheight,\n"
				+ "    });\n"
				+ "    return newstage;\n"
				+ "}\n"*/
				/*+ "function escribe(capa, texto, x, y) {\n"
				+ "    var contexto = capa.getContext();\n"
				+ "    capa.clear();\n"
				+ "    contexto.font = '18pt Calibri';\n"
				+ "    contexto.fillStyle = 'black';\n"
				+ "    contexto.fillText(texto, x, y);\n"
				+ "}\n"*/
				+ "function tooltip(capa, bg, texto, x, y) {\n"
				+ "    var contexto = capa.getContext();\n"
				+ "    capa.clear();\n"
				+ "    bg.setWidth(3 + (texto.length * 8));\n"
				+ "    if ((x+10+bg.getWidth()) >= stage.getWidth()){\n"
				+ "    bg.setX(x-(bg.getWidth()+3));\n"
				+ "    } else {\n"
				+ "    bg.setX(x+10);\n"
				+ "    }\n"
				+ "    bg.setY(y+15);\n"
				+ "    if ((bg.getY()+bg.getHeight()) >= stage.getHeight())\n"
				+ "          bg.setY(y-bg.getHeight());\n"
				+ "    bg.setVisible(true);\n"
				+ "    capa.draw();\n"
				+ "    contexto.font = '10pt Courier New';\n"
				+ "    contexto.fillStyle = 'black';\n"
				+ "    contexto.fillText(texto, bg.getX(), bg.getY()+12);\n"
				+ "}\n"
				//+ "var rowsIDs = new Array();\n"
				//+ "var rowsLabels = new Array();\n"
				//+ "var colsIDs = new Array();\n"
				//+ "var colsLabels = new Array();\n"
				+ "var colsValues = new Array();\n";
				//+ "var columnas;\n"
				//+ "var cambios;\n"
				//+ "function inicializar(){\n";
				//+ "var cambios = [];\n";
	}

	public static final String table1 = 
			
			"function dibujo(stage){\n"
					+ "    var primcol = 0;\n"
					+ "    var prevlong = 0;\n"
					+ "    var nodos = new Kinetic.Layer();\n"
					+ "    var grid = new Kinetic.Layer();\n"
					+ "    var tiplayer = new Kinetic.Layer();\n"
					+ "    var bg = new Kinetic.Rect({\n"
					+ "         x: 0,\n"
					+ "         y: 0,\n"
					+ "         width: 0,\n"
					+ "         height: 15,\n"
					+ "         fill: 'white',\n"
					+ "         stroke: 'black',\n"
					+ "         strokeWidth: 1,\n"
					+ "         visible: false\n"
					+ "         });\n"
					+ "    tiplayer.add(bg);\n"
					+ "for (var n=0;n<(rowsClassIDs.length-offsetR)-1;n++){\n"
					+ "     var fila = new Kinetic.Text({\n"
					+ "         x: 5,\n"
					+ "         y: 35 + (30*n),\n"
					+ "         text: rowsClassLabels[n+offsetR],\n"
					+ "         name: n+offsetR,\n"
					+ "         fontSize: 16,\n"
					+ "         fontFamily: 'Verdana',\n"
					+ "         fill: 'black'\n"
					+ "    });\n"
					+ "    if (fila.getText() == '$'){\n"
			        + "    fila.setText(rowsClassIDs[n+offsetR]);\n"
			        + "    }\n"
					+ "    fila.on('mousemove', function(){\n"
					+ "            var mousePos = stage.getMousePosition();\n"
					+ "            tooltip(tiplayer, bg, onto1+\"#\"+rowsClassIDs[this.getName()]\n"
					+ "                    , mousePos.x, mousePos.y);\n"
					+ "            this.setFill(\"red\");\n"
					+ "    });\n"
					+ "    fila.on('mouseout', function(){\n"
					+ "            this.setFill(\"black\");\n"
					+ "            bg.setVisible(false);\n"
					+ "            tiplayer.clear();\n"
					+ "    });\n"
					+ "    nodos.add(fila);\n"
			        + "    if (fila.getWidth() > primcol){\n"
			        + "    primcol = fila.getWidth();\n"
			        + "    }\n"
			        + "    var line = new Kinetic.Line({\n"
					+ "         points: [0,25+(30*n),stage.getWidth(),25+(30*n)],\n"
					+ "         strokeWidth: 3,\n"
					+ "         lineCap: 'round',\n"
					+ "    });\n"
					+ "    nodos.add(line);\n"
					+ "}\n"
					+ "var j = 0;\n"
					+ "var k = 0;\n"
					+ "if (document.getElementById(\"propchk\").checked){\n"
					+ "while (k>=0 && (k+n < nottoofar)\n"
					+ "   && (k < (rowsPropIDs.length-offsetPR))){\n"
					+ "     var fila = new Kinetic.Text({\n"
					+ "         x: 5,\n"
					+ "         y: 35 + (30*(k+n)),\n"
					+ "         text: rowsPropLabels[k+offsetPR],\n"
					+ "         name: k+offsetPR,\n"
					+ "         fontSize: 16,\n"
					+ "         fontFamily: 'Verdana',\n"
					+ "         fill: 'black'\n"
					+ "    });\n"
					+ "    if (fila.getText() == '$'){\n"
			        + "    fila.setText(rowsPropIDs[k+offsetPR]);\n"
			        + "    }\n"
			        + "    fila.on('mousemove', function(){\n"
					+ "            var mousePos = stage.getMousePosition();\n"
					+ "            tooltip(tiplayer, bg, onto1+\"#\"+rowsPropIDs[this.getName()]\n"
					+ "                    , mousePos.x, mousePos.y);\n"
					+ "            this.setFill(\"red\");\n"
					+ "    });\n"
					+ "    fila.on('mouseout', function(){\n"
					+ "            this.setFill(\"black\");\n"
					+ "            bg.setVisible(false);\n"
					+ "            tiplayer.clear();\n"
					+ "    });\n"
					+ "    nodos.add(fila);\n"
			        + "    if (fila.getWidth() > primcol){\n"
			        + "    primcol = fila.getWidth();\n"
			        + "    }\n"
			        + "    var line = new Kinetic.Line({\n"
					+ "         points: [0,25+(30*(k+n)),stage.getWidth(),25+(30*(k+n))],\n"
					+ "         strokeWidth: 3,\n"
					+ "         lineCap: 'round',\n"
					+ "    });\n"
					+ "    nodos.add(line);\n"
					+ "    k++;\n"
					+ "}\n"
					+ "}\n"
					+ "if (document.getElementById(\"datachk\").checked){\n"
					+ "while (j>=0 && (j+k+n < nottoofar)\n"
					+ "   && (j < (rowsDataIDs.length-offsetDR))){\n"
					+ "     var fila = new Kinetic.Text({\n"
					+ "         x: 5,\n"
					+ "         y: 35 + (30*(j+k+n)),\n"
					+ "         text: rowsDataLabels[j+offsetDR],\n"
					+ "         name: j+offsetDR,\n"
					+ "         fontSize: 16,\n"
					+ "         fontFamily: 'Verdana',\n"
					+ "         fill: 'black'\n"
					+ "    });\n"
					+ "    if (fila.getText() == '$'){\n"
			        + "    fila.setText(rowsDataIDs[j+offsetDR]);\n"
			        + "    }\n"
			        + "    fila.on('mousemove', function(){\n"
					+ "            var mousePos = stage.getMousePosition();\n"
					+ "            tooltip(tiplayer, bg, onto1+\"#\"+rowsDataIDs[this.getName()]\n"
					+ "                    , mousePos.x, mousePos.y);\n"
					+ "            this.setFill(\"red\");\n"
					+ "    });\n"
					+ "    fila.on('mouseout', function(){\n"
					+ "            this.setFill(\"black\");\n"
					+ "            bg.setVisible(false);\n"
					+ "            tiplayer.clear();\n"
					+ "    });\n"
					+ "    nodos.add(fila);\n"
			        + "    if (fila.getWidth() > primcol){\n"
			        + "    primcol = fila.getWidth();\n"
			        + "    }\n"
			        + "    var line = new Kinetic.Line({\n"
					+ "         points: [0,25+(30*(j+k+n)),stage.getWidth(),25+(30*(j+k+n))],\n"
					+ "         strokeWidth: 3,\n"
					+ "         lineCap: 'round',\n"
					+ "    });\n"
					+ "    nodos.add(line);\n"
					+ "    j++;\n"
					+ "}\n"
					+ "}\n"
					+ "if (j+k+n < nottoofar){\n"
					+ "ultfila = 25+(30*(j+k+n));\n"
					+ "} else {\n"
					+ "ultfila = 25+(30*nottoofar);\n"
					+ "}\n"
					+ "var line = new Kinetic.Line({\n"
					+ "    points: [0,ultfila,stage.getWidth(),ultfila],\n"
					+ "    strokeWidth: 3,\n"
					+ "    lineCap: 'round',\n"
					+ "});\n"
					+ "nodos.add(line);\n"
					;
	
	public static final String table2 =
			  //"0];\n"+ 
	          "line = new Kinetic.Line({\n"
			+ "     points: [(20+primcol)+(prevlong)-3, 0, (20+primcol)+(prevlong)-3, ultfila],\n"
			+ "     strokeWidth: 3,\n"
			+ "     lineCap: 'round',\n"
			+ "     });\n"
			+ "nodos.add(line);\n"
			+ "n=offsetC+offsetPC+offsetDC;\n"
			//+ "for (n=0;n<colsValues.length-1;n++){\n"
			//TODO: Ni los valores ni las casillas se dibujan 
			+ "while ((n<=((colsClassIDs.length)+(colsPropIDs.length)+(colsDataIDs.length))) && (((20+primcol)+(prevlong)) <= (stage.getWidth()-120))){\n"
			+ "    var anchocelda = 0;\n"
			+ "    var occupied = new Array();\n"
			+ "    for (var k=0;k<colsValues.length-1;k++){\n"
			//+ "    if (document.getElementById(columnas[n][1][k][1]).checked){\n"
			+ "     if((n <= colsClassIDs.length) && document.getElementById(\"classchk\").checked\n"
		 	+ "      ||(n <= colsClassIDs.length+colsPropIDs.length) && document.getElementById(\"propchk\").checked\n"
		 	+ "      ||(n <= colsClassIDs.length+colsPropIDs.length+colsDataIDs.length) && document.getElementById(\"datachk\").checked){\n"
			+ "     if((colsValues[k][0] == n) && ((offsetR+offsetPR+offsetDR) <= colsValues[k][1]) && ((colsValues[k][1] - (offsetR+offsetPR+offsetDR)) < nottoofar)){\n"
			+ "        if (((colsValues[k][2] != \">\"\n"
			+ "           && colsValues[k][2] != \"<\"\n"
			+ "           && colsValues[k][2] != \"=\") && (document.getElementById(\"others\").checked))\n"
			+ "           || (colsValues[k][2] == \">\" && document.getElementById(\">\").checked)\n"
			+ "           || (colsValues[k][2] == \"<\" && document.getElementById(\"<\").checked)\n"
			+ "           || (colsValues[k][2] == \"=\" && document.getElementById(\"=\").checked)\n"
			+ "           ){\n"
			+ "             if (colsValues[k][3] >= umbral){\n"
			+ "                var cell = new Kinetic.Text({\n"
			+ "                     x: (20+primcol)+(prevlong),\n"
			+ "                     y: 35+(30*(colsValues[k][1]-(offsetR+offsetPR+offsetDR))),\n"
			+ "                     text: colsValues[k][2]+\" \"+colsValues[k][3],\n"
			+ "                     name: (n+\"@\"+k),\n"
			+ "                     id: (colsValues[k][0]+\"@\"+colsValues[k][1]),\n"
			+ "                     fontSize: 16,\n"
			+ "                     fontFamily: 'Verdana',\n"
			+ "                     fill: 'black'\n"
			+ "                });\n"
			+ "                occupied.push(colsValues[k][1]);\n"
			+ "                if (!sessionStorage.occupied){\n"
			+ "                   sessionStorage.occupied = occupied;\n"
			+ "                }else{\n"
			+ "                   sessionStorage.occupied = occupied;\n"
			+ "                }\n"
			+ "                cell.on('mouseover', function(){\n"
			+ "                     if (modo==1){\n"
			+ "                        var nodo = nodos.get('.'+this.getId());\n"
			+ "                        nodo[0].setFill(\"#8AB8E6\");\n"
			+ "                        nodos.draw();\n"
			+ "                     }"
			+ "                });\n"
			+ "                cell.on('mouseout', function(){\n"
			+ "                    if (modo==1){\n"
			+ "                        var nodo = nodos.get('.'+this.getId());\n"
			+ "                        nodo[0].setFill(\"white\");\n"
			+ "                        nodos.draw();\n"
			+ "                    }\n"
			+ "                });\n"
			+ "                cell.on('click', function(){\n"
			+ "                if (modo == 1){\n"
			+ "                    var i = this.getName();\n"
			+ "                    if (document.getElementById(\"rd=\").checked){\n"
			+ "                        colsValues[i.split(\"@\")[1]][2] = \"=\";\n"
			+ "                    }\n"
			+ "                    if (document.getElementById(\"rd<\").checked){\n"
			+ "                        colsValues[i.split(\"@\")[1]][2] = \"<\";\n"
			+ "                    }\n"
			+ "                    if (document.getElementById(\"rd>\").checked){\n"
			+ "                        colsValues[i.split(\"@\")[1]][2] = \">\";\n"
			+ "                    }\n"
			+ "                    colsValues[i.split(\"@\")[1]][3] = parseFloat(document.getElementById(\"valorin\").value);\n"
			+ "               this.setText(colsValues[i.split(\"@\")[1]][2]+\" \"+colsValues[i.split(\"@\")[1]][3]);\n"
			+ "               stage.reset();\n"
			+ "               dibujo(stage);\n"
			+ "               }\n"
			+ "               });\n"
			+ "               grid.add(cell);\n"
			+ "               if (anchocelda < cell.getWidth()){\n"
			+ "                   anchocelda = cell.getWidth();"
			+ "               }\n"
			+ "            }\n"
			+ "        }\n"
			+ "    }\n"
			+ "    }\n"
			+ "    }\n"
			+ "    if(n < colsClassIDs.length){"
		 	+ "    var col = new Kinetic.Text({\n"
			+ "         x: (20+primcol)+(prevlong),\n"
			+ "         y: 0,\n"
			+ "         text: colsClassLabels[n],\n"
			+ "         name: n,\n"
			+ "         fontSize: 16,\n"
			+ "         fontFamily: 'Verdana',\n"
			+ "         fill: 'black'\n"
			+ "    });\n"
			+ "    if (col.getText() == '$'){\n"
	        + "    col.setText(colsClassIDs[n]);\n"
	        + "    }\n"
	        + "    col.on('mousemove', function(){\n"
			+ "            var mousePos = stage.getMousePosition();\n"
		    + "            tooltip(tiplayer, bg, onto2+\"#\"+colsClassIDs[this.getName()]\n"
			+ "                    , mousePos.x, mousePos.y);\n"
			+ "            this.setFill(\"red\");\n"
			+ "    });\n"
			+ "    col.on('mouseout', function(){\n"
			+ "            this.setFill(\"black\");\n"
			+ "            bg.setVisible(false);\n"
			+ "            tiplayer.clear();\n"
			+ "    });\n"
			+ "    nodos.add(col);\n"
	        + "    } else if (n < colsClassIDs.length+colsPropIDs.length){"
	        + "    var col = new Kinetic.Text({\n"
			+ "         x: (20+primcol)+(prevlong),\n"
			+ "         y: 0,\n"
			+ "         text: colsPropLabels[n-colsClassIDs.length],\n"
			+ "         name: n-colsClassIDs.length,\n"
			+ "         fontSize: 16,\n"
			+ "         fontFamily: 'Verdana',\n"
			+ "         fill: 'black'\n"
			+ "    });\n"
			+ "    if (col.getText() == '$'){\n"
	        + "    col.setText(colsPropIDs[n-colsClassIDs.length]);\n"
	        + "    }\n"
	        + "    col.on('mousemove', function(){\n"
			+ "            var mousePos = stage.getMousePosition();\n"
		    + "            tooltip(tiplayer, bg, onto2+\"#\"+colsPropIDs[this.getName()]\n"
			+ "                    , mousePos.x, mousePos.y);\n"
			+ "            this.setFill(\"red\");\n"
			+ "    });\n"
			+ "    col.on('mouseout', function(){\n"
			+ "            this.setFill(\"black\");\n"
			+ "            bg.setVisible(false);\n"
			+ "            tiplayer.clear();\n"
			+ "    });\n"
			+ "    nodos.add(col);\n"
	        + "    } else if (n < colsClassIDs.length+colsPropIDs.length+colsDataIDs.length){"
	        + "    var col = new Kinetic.Text({\n"
			+ "         x: (20+primcol)+(prevlong),\n"
			+ "         y: 0,\n"
			+ "         text: colsDataLabels[n-(colsClassIDs.length+colsPropIDs.length)],\n"
			+ "         name: n-(colsClassIDs.length+colsPropIDs.length),\n"
			+ "         fontSize: 16,\n"
			+ "         fontFamily: 'Verdana',\n"
			+ "         fill: 'black'\n"
			+ "    });\n"
			+ "    if (col.getText() == '$'){\n"
	        + "    col.setText(colsDataIDs[n-(colsClassIDs.length+colsPropIDs.length)]);\n"
	        + "    }\n"
	        + "    col.on('mousemove', function(){\n"
			+ "            var mousePos = stage.getMousePosition();\n"
		    + "            tooltip(tiplayer, bg, onto2+\"#\"+colsDataIDs[this.getName()]\n"
			+ "                    , mousePos.x, mousePos.y);\n"
			+ "            this.setFill(\"red\");\n"
			+ "    });\n"
			+ "    col.on('mouseout', function(){\n"
			+ "            this.setFill(\"black\");\n"
			+ "            bg.setVisible(false);\n"
			+ "            tiplayer.clear();\n"
			+ "    });\n"
			+ "    nodos.add(col);\n"
	        + "    }\n"
			+ "if (anchocelda < col.getWidth()){\n"
			+ "    anchocelda = col.getWidth();\n"
			+ "   }\n"
			//+ "for (k=0;k<rowsIDs.length-1;k++){\n"
			+ "for (k=offsetR+offsetPR+offsetDR;k<nottoofar+offsetR+offsetPR+offsetDR;k++){\n"
			+ "    if (25+(30*(k-(offsetR+offsetPR+offsetDR))) < ultfila){\n"
			+ "    var pos = occupied.indexOf(k);\n"
			+ "    var hole = new Kinetic.Rect({\n"
			+ "         x: (17+primcol+prevlong),\n"
			+ "         y: 25+(30*(k-(offsetR+offsetPR+offsetDR))),\n"
			+ "         name: (n+\"@\"+k),\n"
			+ "         width: 10+anchocelda,\n"
			+ "         height: 30,\n"
			+ "         fill: 'white',\n"
			+ "         stroke: 'black',\n"
			+ "         strokeWidth: 3\n"
			+ "         }\n"
			+ "    );\n"
			+ "nodos.add(hole);\n"
			+ "hole.on('mouseover', function(){\n"
			+ "        if (modo==1){\n"
			+ "           this.setFill(\"#8AB8E6\");\n"
			+ "           nodos.draw();\n"
			+ "        }\n"
			+ "});\n"
			+ "hole.on('mouseout', function(){\n"
			+ "if (modo==1){\n"
			+ "    this.setFill(\"white\");\n"
			+ "    nodos.draw();\n"
			+ "    }\n"
			+ "});\n"
			+ "if (pos == -1){\n"
			+ "hole.on('click', function(){\n"
			+ "       if (modo==1){\n"
			+ "           var i = this.getName();\n"
			+ "           var newpair = [i.split(\"@\")[0],i.split(\"@\")[1],\"=\",\"0\"];\n"
			+ "           if (document.getElementById(\"rd=\").checked){\n"
			+ "              newpair[2] = \"=\";\n"
			+ "           }\n"
			+ "           if (document.getElementById(\"rd<\").checked){\n"
			+ "              newpair[2] = \"<\";\n"
			+ "           }\n"
			+ "           if (document.getElementById(\"rd>\").checked){"
			+ "              newpair[2] = \">\";\n"
			+ "           }\n"
			+ "           newpair[3] = parseFloat(document.getElementById(\"valorin\").value);\n"
			+ "           var limit = colsValues.length;\n"
			+ "           colsValues.pop();\n"
			+ "           colsValues.push(newpair);\n"
			+ "           colsValues.push(0);\n"
			//+ "           this.hide();\n"
			//+ "           nodos.draw();\n"
			//+ "           escribe(mensaje, \"Added \"+newpair[1]+newpair[2]+\" in \"+i.split(\"@\")[0]"
			//+ "                            +\", \"+i.split(\"@\")[1]);\n"
			+ "           var cell = new Kinetic.Text({"
			+ "                          x: 3+this.getX(),\n"
			+ "                          y: 10+this.getY(),\n"
			+ "                          text: newpair[2]+\" \"+newpair[3],\n"
			+ "                          name: ((i.split(\"@\")[0])+\"@\"+limit),\n"
			+ "                          id: (newpair[0]+\"@\"+newpair[1]),\n"
			+ "                          fontSize: 16,\n"
			+ "                          fontFamily: 'Verdana',\n"
			+ "                          fill: 'black'\n"
			+ "                          });\n"
			+ "               grid.add(cell);\n"
//			+ "           }else{\n"
//			+ "               cell.setText(newpair[1]+\" \"+newpair[2]);\n"
//			+ "           }\n"
			+ "           stage.reset();\n"
			+ "           dibujo(stage);\n"
			+ "     }\n"
			+ "   });\n"
			+ "} else {\n"
			+ "hole.on('click', function(){\n"
			+ "        if (modo==1){\n"
			+ "            var i = this.getName();\n"
			+ "			   var newpair = [i.split(\"@\")[0],i.split(\"@\")[1],\"=\",\"0\"];\n"
			+ "            if (document.getElementById(\"rd=\").checked){\n"
			+ "               newpair[2] = \"=\";\n"
			+ "            }\n"
			+ "            if (document.getElementById(\"rd<\").checked){\n"
			+ "               newpair[2] = \"<\";\n"
			+ "            }\n"
			+ "            if (document.getElementById(\"rd>\").checked){"
			+ "               newpair[2] = \">\";\n"
			+ "            }\n"
			+ "            newpair[3] = parseFloat(document.getElementById(\"valorin\").value);\n"
			+ "            var cells = grid.get('#'+i);\n"
			+ "            var j = cells[0].getName();\n"
			+ "            colsValues[j.split(\"@\")[1]][2] = newpair[2];\n"
			+ "            colsValues[j.split(\"@\")[1]][3] = newpair[3];\n"
			+ "            cells[0].setText(newpair[1]+\" \"+newpair[2]);\n"
			+ "           stage.reset();\n"
			+ "           dibujo(stage);\n"
			+ "     }\n"
			+ "   });\n"
			+ "}\n"
			+ "}\n"
			+ "}\n"
			+ "prevlong += 10+anchocelda;\n"
			+ "    var line = new Kinetic.Line({\n"
			+ "        points: [(20+primcol)+(prevlong)-3, 0, (20+primcol)+(prevlong)-3, ultfila],\n"
			+ "        strokeWidth: 3,\n"
			+ "        lineCap: 'round',\n"
			+ "    });\n"
			+ "    nodos.add(line);\n"
			+ "n++;}\n";

	public static final String table3 =
			//"stage.add(mensaje);\n" +
			"stage.add(nodos);\n"+
	        "stage.add(grid);\n"+
			"stage.add(tiplayer);\n" +
	        "};\n" +
	        "inicializar();\n" +
			"dibujo(stage);\n" +
			"</script>\n" +
			"</body>\n" +
			"</html>\n";

	public static String treehead(int height, String onto1, String onto2){
		return "<!DOCTYPE html>\n"
				+ "<html>\n"
				+ "<title>OntoVis - Tree mode</title>\n"
				+ "<body>\n"
				+ "<div id=\"container\">\n"
				+ "<div id=\"header\" style=\"background-color:#8AA8E6;\">\n"
				//+ "<h1 style=\"margin-bottom:0;\">Visualizer: Tree mode</h1></div>\n"
				+ "<h1 style=\"margin-top:0;margin-bottom:0;\"><img src=\"./logoOntoVis3.png\" alt=\"OntoVis\">Tree Mode</h1></div>\n"
				+ "<div id=\"menu\" style=\"background-color:#8AB8E6;height:100%;width:120px;float:left;\">\n"
				//+ alto
				+ "<p><input type=\"text\" id=\"baremo\" size=\"4\" maxLength=\"6\" value=\"0.0\"></p>\n"
				+ "<p>Show<br>"
				+ "<input type=\"checkbox\" id=\"=\">="
				+ "<input type=\"checkbox\" id=\"<\"><"
				+ "<input type=\"checkbox\" id=\">\">><br>"
				+ "<input type=\"checkbox\" id=\"others\">Others\n"
				+ "<br><br><input type=\"checkbox\" id=\"classchk\">Classes"
				+ "<br><input type=\"checkbox\" id=\"propchk\">Properties"
				+ "<br><input type=\"checkbox\" id=\"datachk\">Datatypes"
				+ "<p><button onclick=\"filtro()\" id=\"botfil\" type=\"button\">Filter</button></p>\n"
				+ "<p><input type=\"checkbox\" id=\"botedi\" onclick=\"editor()\">Edit mode</p>\n"
				+ "<input type=\"radio\" name=\"rel\" id=\"rd=\" value=\"=\" disabled=\"true\" checked=\"true\">="
				+ "<input type=\"radio\" name=\"rel\" id=\"rd<\" value=\"<\" disabled=\"true\"><"
				+ "<input type=\"radio\" name=\"rel\" id=\"rd>\" value=\">\" disabled=\"true\">>\n" +
				  "<p><input type=\"text\" id=\"valorin\" size=\"4\" maxLength=\"6\" value=\"0.0\" disabled=\"true\"></p>" +
				  "<p><button onclick=\"fijarCambios()\" type=\"button\">Accept</button></p>\n" + 
				  "<p><button onclick=\"hacerCopia()\" type=\"button\">Save Copy</button></p>\n"
				+ "<p><button onclick=\"history.back()\" type=\"button\">Back</button></p>\n"
				+ "Scroll using<br>"
				+ "Q/A & Up/Down keys"
				+ "</div>\n"
				+ "<div id=\"content\" style=float:left;\">\n"
				+ "</div>\n"
				+ "<div id=\"footer\" style=\"background-color:#8AB8E6;clear:both;text-align:center;\">\n"
				+ "© Victor Albir 2012-2013</div>\n"
				+ "</div>"
				//+ "<script src=\"kinetic-v4.0.5.min.js\"></script>"
				+ "<script src=\"kinetic-v4.3.3.min.js\"></script>"
				+ "<script>\n"
				+ "function filtro(){\n"
				+ "stage.reset();\n"
				+ "umbral=parseFloat(document.getElementById(\"baremo\").value);\n"
				+ "if (document.getElementById(\"datachk\").checked && datachkbefore == 1){\n" +
				  "datachkbefore = 0;\n" +
				  "}\n"				
				+ "if (document.getElementById(\"propchk\").checked && propchkbefore == 1){\n"
				+ "    propchkbefore = 0;\n"
				+ "}\n"
				+ "if (document.getElementById(\"classchk\").checked && classchkbefore == 1){\n"
				+ "    classchkbefore = 0;\n"
				+ "    offsetPA = 0;\n"
				+ "    offsetPB = 0;\n"
				+ "    offsetDA = 0;\n"
				+ "    offsetDB = 0;\n"
				+ "    inicializar();\n"
				+ "}\n"
				+ "if (!document.getElementById(\"datachk\").checked){\n"
				+ "    datachkbefore = 1;\n"
				+ "    lineas.removeChildren();\n"
				+"}\n"
				+ "if (!document.getElementById(\"propchk\").checked){\n"
				+ "    propchkbefore = 1;\n"
				+ "    lineas.removeChildren();\n"
				+ "}\n"
				+ "if (!document.getElementById(\"classchk\").checked){\n"
				+ "    offsetA = collapsedA.length-1;\n"
				+ "    offsetB = collapsedB.length-1;\n"
				+ "    classchkbefore = 1;\n"
				+ "    lineas.removeChildren();\n"
				+ "}\n"
				// + "stage = reset(stage);\n"
				/*
				 * + "    stage.remove();\n" +
				 * "    stage = new Kinetic.Stage({\n" +
				 * "        container: \"content\",\n" +
				 * "        width: stwidth,\n" + "        height: stheight,\n" +
				 * "    });\n"
				 */
				+ "dibujo(stage);\n"
				+ "}\n"
				+ "function editor(){\n"
				+ "    if (modo == 0){\n"
				+ "    document.getElementById(\"rd=\").disabled = false;\n"
				+ "    document.getElementById(\"rd<\").disabled = false;\n"
				+ "    document.getElementById(\"rd>\").disabled = false;\n"
				+ "    document.getElementById(\"valorin\").disabled = false;\n"
				+ "    document.getElementById(\"=\").checked = true;\n"
				+ "    document.getElementById(\"<\").checked = true;\n"
				+ "    document.getElementById(\">\").checked = true;\n"
				+ "    document.getElementById(\"others\").checked = true;\n"
			    + "    document.getElementById(\"=\").disabled = true;\n"
				+ "    document.getElementById(\"<\").disabled = true;\n"
				+ "    document.getElementById(\">\").disabled = true;\n"
				+ "    document.getElementById(\"others\").disabled = true;\n"
				+ "    document.getElementById(\"baremo\").disabled = true;\n"
				+ "    document.getElementById(\"botfil\").disabled = true;\n"
				+ "    document.getElementById(\"classchk\").disabled = true;\n"
				+ "    document.getElementById(\"propchk\").disabled = true;\n"
				+ "    document.getElementById(\"datachk\").disabled = true;\n"
				+ "    umbral = 0.0;\n"
				+ "    collapsedA = classesA.slice(0);\n"
				+ "    collapsedAlevels = levelsA.slice(0);\n"
				+ "    collapsedB = classesB.slice(0);\n"
				+ "    collapsedBlevels = levelsB.slice(0);\n"
				+ "    clickedA = [];\n"
				+ "    clickedB = [];\n"
				+ "    heightsA = [];\n"
				+ "    heightsB = [];\n"
				+ "    offsetPA = 0;\n"
				+ "    offsetPB = 0;\n"
				+ "    offsetDA = 0;\n"
				+ "    offsetDB = 0;\n"
				+ "    modo = 1;\n"
				+ "    stage.reset();\n"
				/*+ "    stage.destroy();\n"
				+ "    stage = new Kinetic.Stage({\n"
				+ "        container: \"content\",\n"
				+ "        width: stwidth,\n"
				+ "        height: stheight,\n"
				+ "    });\n"*/
		        + "    dibujo(stage);\n"
				+ "    } else {\n"
				+ "    document.getElementById(\"rd=\").disabled = true;\n"
				+ "    document.getElementById(\"rd<\").disabled = true;\n"
				+ "    document.getElementById(\"rd>\").disabled = true;\n"
				+ "    document.getElementById(\"valorin\").disabled = true;\n"
				+ "    document.getElementById(\"=\").disabled = false;\n"
				+ "    document.getElementById(\"<\").disabled = false;\n"
				+ "    document.getElementById(\">\").disabled = false;\n"
				+ "    document.getElementById(\"others\").disabled = false;\n"
				+ "    document.getElementById(\"baremo\").disabled = false;\n"
				+ "    document.getElementById(\"botfil\").disabled = false;\n"
				+ "    document.getElementById(\"classchk\").disabled = false;\n"
				+ "    document.getElementById(\"propchk\").disabled = false;\n"
				+ "    document.getElementById(\"datachk\").disabled = false;\n"
				+ "    modo = 0;\n"
				+ "    stage.reset();\n"
				+ "    inicializar();\n"
				//+ "stage = reset(stage);\n"
				/*+ "    stage.destroy();\n"
				+ "    stage = new Kinetic.Stage({\n"
				+ "        container: \"content\",\n"
				+ "        width: stwidth,\n"
				+ "        height: stheight,\n"
				+ "    });\n"*/
		        + "    dibujo(stage);\n"
				+ "    }\n"
				+ "}\n"
				+ "function fijarCambios(){"
				+ "    if (modo == 1){\n"
				+ "    document.getElementById(\"rd=\").disabled = true;\n"
				+ "    document.getElementById(\"rd<\").disabled = true;\n"
				+ "    document.getElementById(\"rd>\").disabled = true;\n"
				+ "    document.getElementById(\"valorin\").disabled = true;\n"
				+ "    document.getElementById(\"=\").disabled = false;\n"
				+ "    document.getElementById(\"<\").disabled = false;\n"
				+ "    document.getElementById(\">\").disabled = false;\n"
				+ "    document.getElementById(\"others\").disabled = false;\n"
				+ "    document.getElementById(\"baremo\").disabled = false;\n"
				+ "    document.getElementById(\"botfil\").disabled = false;\n"
				+ "    document.getElementById(\"botedi\").checked = false;\n"
				+ "    document.getElementById(\"classchk\").disabled = false;\n"
				+ "    document.getElementById(\"propchk\").disabled = false;\n"
				+ "    document.getElementById(\"datachk\").disabled = false;\n"
				+ "    modo = 0;\n"
				+ "    stage.reset();\n"
				//+ "stage = reset(stage);\n"
				/*+ "    stage.remove();\n"
				+ "    stage = new Kinetic.Stage({\n"
				+ "        container: \"content\",\n"
				+ "        width: stwidth,\n"
				+ "        height: stheight,\n"
				+ "    });\n"*/
				+ "    dibujo(stage);\n"
				+ "    }\n"
				+ "}\n"
				+ "function hacerCopia(){\n"
				// TODO: funcion que avisa al servidor para construir el fichero
				// de ontologia modificado
				+ "var xmlhttp;\n"
				+ "if (window.XMLHttpRequest)\n"
				+ "  {// code for IE7+, Firefox, Chrome, Opera, Safari\n"
				+ "  xmlhttp=new XMLHttpRequest();\n"
				+ "  }\n"
				+ "else\n"
				+ "  {// code for IE6, IE5\n"
				+ "  xmlhttp=new ActiveXObject(\"Microsoft.XMLHTTP\");\n"
				+ "  }\n"
				+ "xmlhttp.open(\"POST\",\"treeCopy.jsp\",false);\n"
				//+ "xmlhttp.send(\"chng=\"+cambios.join())\n;"
				+ "xmlhttp.setRequestHeader(\"Content-type\",\"application/x-www-form-urlencoded\");\n"
				+ "xmlhttp.send(\"q=\"+classesA.concat(propertiesA.concat(datatypesA))+\"@\"+classesB.concat(propertiesB.concat(datatypesB))+\"@\"+uniones+\"@"+onto1+"@"+onto2+"\");\n"
				+ "location.href='/ontovis/alignment.rdf'\n"
				+ "}\n"
				+ "document.getElementById(\"=\").checked=true;\n"
				+ "document.getElementById(\"<\").checked=true;\n"
				+ "document.getElementById(\">\").checked=true;\n"
				+ "document.getElementById(\"others\").checked=true;\n"
				+ "document.getElementById(\"classchk\").checked=true;\n"
				+ "document.getElementById(\"propchk\").checked=true;\n"
				+ "document.getElementById(\"datachk\").checked=true;"
				+ "var classchkbefore = 0;"
				+ "var propchkbefore = 0;"
				+ "var datachkbefore = 0;"
				+ "var umbral = 0;\n"
				+ "var modo = 0;\n"
				+ "var w=window,d=document,e=d.documentElement,g=d.getElementsByTagName('body')[0],x=w.innerWidth||e.clientWidth||g.clientWidth,y=w.innerHeight||e.clientHeight||g.clientHeight;\n"
				+ "var stage = new Kinetic.Stage({\n"
				+ "                container: \"content\",\n"
				+ "                width: x - 200,\n"
				+ "                height: y - 99,\n"
				+ "                });\n"
				+ "var offsetA = 0;\n"
				+ "var offsetPA = 0;\n"
				+ "var offsetDA = 0;\n"
				+ "var offsetB = 0;\n"
				+ "var offsetPB = 0;\n"
				+ "var offsetDB = 0;\n"
				+ "var nottoofar = parseInt(stage.getHeight()/30);\n"
				+ "document.onkeydown = function(evt){"
				+ "    evt = evt || window.event;"
				+ "    switch (evt.keyCode) {"
				+ "        case 38:"
				+ "           upArrow();"
				+ "           break;"
				+ "        case 40:"
				+ "           downArrow();"
				+ "           break;"
				+ "        case 65:"
				+ "           aKey();"
				+ "           break;"
				+ "        case 81:"
				+ "           qKey();"
				+ "           break;"
				+ "    }"
				+ "};"
				+ "function upArrow(){\n"
				+ "    if (document.getElementById(\"classchk\").checked\n"
				+ "        && offsetB > 0 && offsetPB == 0){\n"
				+ "       offsetB = offsetB - 1;\n"
				+ "       lineas.removeChildren();\n"
				+ "       stage.reset();\n"
				+ "       dibujo(stage);\n"
				+ "        return;\n"
				+ "    }\n"
				+ "    if (offsetPB > 0 && offsetDB == 0){\n"
				+ "       offsetPB = offsetPB - 1;\n"
				+ "       lineas.removeChildren();\n"
				+ "       stage.reset();\n"
				+ "       dibujo(stage);\n"
				+ "        return;\n"
				+ "    }\n"
				+ "    if (offsetDB > 0){\n"
				+ "       offsetDB = offsetDB - 1;\n"
				+ "       lineas.removeChildren();\n"
				+ "       stage.reset();\n"
				+ "       dibujo(stage);\n"
				+ "        return;\n"
				+ "    }\n"
				+ "}\n"
				+ "function downArrow(){\n"
				+ "    if (document.getElementById(\"datachk\").checked\n"
				+ "    && ((document.getElementById(\"propchk\").checked && offsetPB == propertiesB.length) || !document.getElementById(\"propchk\").checked)\n"
				+ "    && ((document.getElementById(\"classchk\").checked && offsetB == collapsedB.length-1) || !document.getElementById(\"classchk\").checked)\n"
				+ "    && offsetDB <= datatypesB.length-nottoofar){\n"
				+ "        offsetDB = offsetDB + 1;\n"
				+ "        lineas.removeChildren();\n"
				+ "        stage.reset();\n"
				+ "        dibujo(stage);\n"
				+ "        return;\n"
				+ "    }\n"
				+ "    if (document.getElementById(\"propchk\").checked"
				+ "    && ((document.getElementById(\"classchk\").checked && offsetB == collapsedB.length-1)\n"
				+ "    || !document.getElementById(\"classchk\").checked)\n"
				+ "    && (!document.getElementById(\"datachk\").checked\n"
				+ "    || document.getElementById(\"datachk\").checked && (propertiesB.length - offsetPB + datatypesB.length) >= nottoofar && offsetPB < propertiesB.length\n"
				+ "    || offsetPB <= propertiesB.length-nottoofar)){\n"
				+ "        offsetPB = offsetPB + 1;\n"
				+ "        lineas.removeChildren();\n"
				+ "        stage.reset();\n"
				+ "        dibujo(stage);\n"
				+ "        return;\n"
				+ "    }\n"
				+ "    if (document.getElementById(\"classchk\").checked &&\n"
				+ "    ((document.getElementById(\"propchk\").checked && collapsedB.length - offsetB + propertiesB.length >= nottoofar)||\n"
				+ "     (document.getElementById(\"datachk\").checked && (collapsedB.length - offsetB + datatypesB.length >= nottoofar) && offsetB < collapsedB.length-1)\n"
				+ "    || offsetB < collapsedB.length-nottoofar)){\n"
				+ "        offsetB = offsetB + 1;\n"
				+ "        lineas.removeChildren();\n"
				+ "        stage.reset();\n"
				+ "        dibujo(stage);\n"
				+ "        return;\n"
				+ "    }\n"
				+ "}\n"
				+ "function qKey(){\n"
				+ "    if (document.getElementById(\"classchk\").checked\n"
				+ "       && offsetA > 0 && offsetPA == 0){\n"
				+ "       offsetA = offsetA - 1;\n"
				+ "       lineas.removeChildren();\n"
				+ "       stage.reset();\n"
				+ "       dibujo(stage);\n"
				+ "        return;\n"
				+ "    }\n"
				+ "    if (offsetPA > 0 && offsetDA == 0){\n"
				+ "       offsetPA = offsetPA - 1;\n"
				+ "       lineas.removeChildren();\n"
				+ "       stage.reset();\n"
				+ "       dibujo(stage);\n"
				+ "        return;\n"
				+ "    }\n"
				+ "    if (offsetDA > 0){\n"
				+ "       offsetDA = offsetDA - 1;\n"
				+ "       lineas.removeChildren();\n"
				+ "       stage.reset();\n"
				+ "       dibujo(stage);\n"
				+ "        return;\n"
				+ "    }\n"
				+ "}"
				+ "function aKey(){\n"
				+ "    if (document.getElementById(\"datachk\").checked\n"
				+ "    && ((document.getElementById(\"propchk\").checked && offsetPA  == propertiesA.length) || !document.getElementById(\"propchk\").checked)\n"
				+ "    && ((document.getElementById(\"classchk\").checked && offsetA == collapsedA.length-1) || !document.getElementById(\"classchk\").checked)\n"
				+ "    && offsetDA <= datatypesB.length-nottoofar){\n"
				+ "        offsetDA = offsetDA + 1;\n"
				+ "        lineas.removeChildren();\n"
				+ "        stage.reset();\n"
				+ "        dibujo(stage);\n"
				+ "        return;\n"
				+ "    }\n"
				+ "    if (document.getElementById(\"propchk\").checked"
				+ "    && ((document.getElementById(\"classchk\").checked && offsetA == collapsedA.length-1)\n"
				+ "    || !document.getElementById(\"classchk\").checked)\n"
				+ "    && (!document.getElementById(\"datachk\").checked\n"
				+ "    || document.getElementById(\"datachk\").checked && (propertiesA.length - offsetPA + datatypesA.length) >= nottoofar && offsetPA < propertiesA.length\n"
				+ "    || offsetPA <= propertiesA.length-nottoofar)){\n"
				+ "        offsetPA = offsetPA + 1;\n"
				+ "        lineas.removeChildren();\n"
				+ "        stage.reset();\n"
				+ "        dibujo(stage);\n"
				+ "        return;\n"
				+ "    }\n"
				+ "    if (document.getElementById(\"classchk\").checked &&\n"
				+ "    ((document.getElementById(\"propchk\").checked && collapsedA.length - offsetA + propertiesA.length >= nottoofar)||\n"
				+ "     (document.getElementById(\"datachk\").checked && (collapsedA.length - offsetA + datatypesA.length >= nottoofar) && offsetA < collapsedA.length-1)\n"
				+ "    || offsetA < collapsedA.length-nottoofar)){\n"
				+ "        offsetA = offsetA + 1;\n"
				+ "        lineas.removeChildren();\n"
				+ "        stage.reset();\n"
				+ "        dibujo(stage);\n"
				+ "        return;\n"
				+ "    }\n"
				+ "}\n"
				/*+ "var stwidth = (1200*0.9);\n"
				+ "var stheight = "	+ height+ ";\n"
			    + "    var stage = new Kinetic.Stage({\n"
				+ "        container: \"content\",\n"
				+ "        width: stwidth,\n"
				+ "        height: stheight,\n"
				+ "    });\n"*/
				+ "var mensaje = new Kinetic.Layer();\n"
				+ "var onto1 = \""+onto1+"\";\n"
				+ "var onto2 = \""+onto2+"\";\n"
				+ "function escribe(capa, texto, x, y){\n"
				+ "    var contexto = capa.getContext();\n"
				+ "    capa.clear();\n"
				+ "    contexto.font = '18pt Calibri';\n"
				+ "    contexto.fillStyle = 'black';\n"
				+ "    contexto.fillText(texto, x, y);\n"
				+ "}\n"
				+ "function tooltip(capa, bg, texto, x, y){\n"
				+ "    var contexto = capa.getContext();\n"
				+ "    capa.clear();\n"
				+ "    bg.setWidth(3 + (texto.length * 8));\n"
				+ "    if ((x+10+bg.getWidth()) >= stage.getWidth()){\n"
				+ "       bg.setX(x-(bg.getWidth()+3));\n"
				+ "    } else {\n" +
				  "       bg.setX(x+10);\n"
				+ "    }\n"
				+ "    bg.setY(y+15);\n"
				+ "    if ((bg.getY()+bg.getHeight()) >= stage.getHeight())\n" +
				  "       bg.setY(y-bg.getHeight());\n"
				+ "    bg.setVisible(true);\n"
				+ "    capa.draw();\n"
				+ "    contexto.font = '10pt Courier New';\n"
				+ "    contexto.fillStyle = 'black';\n"
				+ "    contexto.fillText(texto, bg.getX(), bg.getY()+12);\n"
				+ "}\n"
				+ "var classesA;\n"
				+ "var levelsA;\n"
				+ "var classLabelsA;\n"
				+ "var propertiesA;\n"
				+ "var propertyLabelsA;\n"
				+ "var datatypesA;\n"
				+ "var datatypeLabelsA;\n"
				+ "var classesB;\n"
				+ "var levelsB;\n"
				+ "var classLabelsB;\n"
				+ "var propertiesB;\n"
				+ "var propertyLabelsB;\n"
				+ "var datatypesB;\n"
				+ "var datatypeLabelsB;\n"
				+ "var uniones;\n"
				+ "var collapsedA;\n"
				+ "var collapsedAlevels;\n"
				+ "var collapsedB;\n"
				+ "var collapsedBlevels;\n"
				+ "var clickedA;\n"
				+ "var heightsA;\n"
				+ "var clickedB;\n"
				+ "var heightsB;\n"
				// + "var newpairA;\n"
				// + "var newpairB;\n"
				+ "function inicializar(){\n"
				;
	}

	public static String join(int a, int b, String signo, String valor){
		//return "[\""+signo+"\", "+valor+", [280, "+(45+(a*30))+", 400, "+(45+(a*30))+", 400, "+(45+(b*30))+", 520, "+(45+(b*30))+", 520, "+(50+(b*30))+", 395, "+(50+(b*30))+", 395, "+(50+(a*30))+", 280, "+(50+(a*30))+"]], ";
		return "[\""+signo+"\", "+valor+", "+a+","+b+"], ";
	}

	public static final String tree1 = 
              "0];\n"
			+ "    sessionStorage.newpairA = \"\";\n"
			+ "    sessionStorage.newpairB = \"\";\n"
			+ "    collapsedA = classesA.slice(0);\n"
			+ "    collapsedAlevels = levelsA.slice(0);\n"
			+ "    collapsedB = classesB.slice(0);\n"
			+ "    collapsedBlevels = levelsB.slice(0);\n"
			+ "    clickedA = new Array();\n"
			+ "    clickedB = new Array();\n"
			+ "    heightsA = new Array();\n"
			+ "    heightsB = new Array();\n"
			+ "}\n"
			+ "    var lineas = new Kinetic.Layer();\n"
			+ "function checkPos(pos,heights,offset){\n"
			+ "var newpos = pos - offset;\n"
			+ "for (var k=0;k<heights.length;k++){\n"
			//+ "     if ((pos < offsetR) || ((pos - offsetR) >= nottoofar))\n"
			//+ "         return -1;\n" 
			+ "     if (heights[k][0] < pos && heights[k][0]+heights[k][1] >= pos)\n"
			+ "         return -1;\n"
			+ "     if ((heights[k][0]+heights[k][1]) < pos)\n"
			+ "         newpos = (newpos-heights[k][1]);\n"
			+ "}\n"
			+ "if (newpos < 0 || newpos >= nottoofar-1)\n"
			+ "   return -1;\n"
			+ "else\n"
			+ "   return newpos;\n"
			+ "}\n"
			+ "function checkA(position){\n"
			+ "if (!document.getElementById(\"classchk\").checked\n"
			+ "    && position < classIDsA.length){\n"
			+ "    return -1;\n"
			+ "} else if (!document.getElementById(\"propchk\").checked\n"
			+ "    && position >= classIDsA.length && position < propertiesA.length){\n"
			+ "    return -1;\n"
			+ "} else if (!document.getElementById(\"datachk\").checked\n"
			+ "    && position >= propertiesA.length && position < datatypesA.length){\n"
			+ "    return -1;\n"
			+ "}\n"
			+ "return checkPos(position,heightsA,(offsetA+offsetPA+offsetDA));\n"
			+ "}\n"
			+ "function checkB(position){\n"
			+ "if (!document.getElementById(\"classchk\").checked\n"
			+ "    && position < classIDsB.length){\n"
			+ "    return -1;\n"
			+ "} else if (!document.getElementById(\"propchk\").checked\n"
			+ "    && position >= classIDsB.length && position < propertiesB.length){\n"
			+ "    return -1;\n"
			+ "} else if (!document.getElementById(\"datachk\").checked\n"
			+ "    && position >= propertiesB.length && position < datatypesB.length){"
			+ "    return -1\n"
			+ "}\n"
			+ "return checkPos(position,heightsB,(offsetB+offsetPB+offsetDB));\n"
			+ "}\n"
			+ "function checkMarkA(position){\n"
			+ "   var index = classesA.indexOf(collapsedA[position]);\n"
			+ "   if ((index == levelsA.length-1) || (levelsA[index] >= levelsA[index+1])){"
			+ "     return -1;\n"
			+ "   } else {\n"
			+ "     return 0;\n"
			+ "   }\n"
			+ "}\n"
			+ "function checkMarkB(position){\n"
			+ "   var index = classesB.indexOf(collapsedB[position]);\n"
			+ "   if ((index == levelsB.length-1) || (levelsB[index] >= levelsB[index+1])){"
			+ "     return -1;\n"
			+ "   } else {\n"
			+ "     return 0;\n"
			+ "   }\n"
			+ "}\n"
			//TODO: cambiar el texto de la unión si existe la union
			//      (clickedItem.getName() en clickActionA es n / posiciónA)
			+ "function clickActionFinisher(){\n"
			+ "   var union = lineas.get('#'+sessionStorage.newpairA+\"@\"+sessionStorage.newpairB);\n"
			+ "   if (union.length == 0){\n"
			+ "   uniones.pop();\n"
			+ "   if (document.getElementById(\"rd=\").checked){\n"
			+ "      uniones.push([\"=\",document.getElementById(\"valorin\").value, Number(sessionStorage.newpairA), Number(sessionStorage.newpairB)]);\n"
			+ "   }\n"
			+ "   if (document.getElementById(\"rd<\").checked){\n"
			+ "      uniones.push([\"<\",document.getElementById(\"valorin\").value, Number(sessionStorage.newpairA), Number(sessionStorage.newpairB)]);\n"
			+ "   }\n"
			+ "   if (document.getElementById(\"rd>\").checked){\n"
			+ "      uniones.push([\">\",document.getElementById(\"valorin\").value, Number(sessionStorage.newpairA), Number(sessionStorage.newpairB)]);\n"
			+ "   }\n"
			+ "   uniones.push(0);\n"
			+ "   sessionStorage.newpairA=\"\";\n"
			+ "   sessionStorage.newpairB=\"\";\n"
			+ "   lineas.removeChildren();\n"
			+ "   stage.reset();\n"
			+ "   dibujo(stage);\n"
			+ "   } else {\n"
			+ "   var index = union[0].getName();\n"
			+ "   if (document.getElementById(\"rd=\").checked){\n"
			+ "      uniones[index][0] = \"=\";\n"
			+ "   }\n"
			+ "   if (document.getElementById(\"rd<\").checked){\n"
			+ "      uniones[index][0] = \"<\";\n"
			+ "   }\n"
			+ "   if (document.getElementById(\"rd>\").checked){\n"
			+ "      uniones[index][0] = \">\";\n"
			+ "   }\n"
			+ "   uniones[index][1] = parseFloat(document.getElementById(\"valorin\").value);\n"
			+ "   uniones[index][2] = Number(sessionStorage.newpairA);\n"
			+ "   uniones[index][3] = Number(sessionStorage.newpairB);\n"
			//+ "   var valor = lineas.get('.'+sessionStorage.newpairA+\"@\"+sessionStorage.newpairB);\n"
			//+ "   valor[0].setText(uniones[index][0]+\" \"+uniones[index][1]);\n"
			+ "   sessionStorage.newpairA=\"\";\n"
			+ "   sessionStorage.newpairB=\"\";\n"
			+ "   lineas.removeChildren();\n"
			+ "   stage.reset();\n"
			+ "   dibujo(stage);\n"
			+ "   }\n"
			+ "};"
			+ "function clickActionA(clickedItem,collection){\n"
			+ "   if (modo == 0){\n"
			+ "       var isClicked = clickedA.indexOf(collapsedA[clickedItem.getName()]);\n"
			+ "       if (isClicked == -1){\n"
			+ "           var prevLevel = collapsedAlevels[clickedItem.getName()];\n"
			+ "           var collapseATo = collapsedAlevels.slice(clickedItem.getName()+1).indexOf(prevLevel);\n"
			+ "           var collapseATo2 = collapsedAlevels.slice(clickedItem.getName()+1).indexOf(prevLevel-1);\n"
			+ "           if (collapseATo2 >= 0 && (collapseATo == -1 || collapseATo2 < collapseATo)){\n"
			+ "               collapseATo = collapseATo2;\n"
			+ "           }\n"
			+ "           if (collapseATo > 0 &&\n"
			+ "           collapsedAlevels[(clickedItem.getName()+collapseATo-1)] >= prevLevel){\n"
			+ "			      collapsedA.splice(clickedItem.getName()+1,collapseATo);\n"
			+ "               heightsA.push([classesA.indexOf(collapsedA[clickedItem.getName()]),collapseATo]);\n"
			+ "               collapsedAlevels.splice(clickedItem.getName()+1,collapseATo);\n"
			+ "               clickedA.push(collapsedA[clickedItem.getName()]);\n"
			+ "           } else "
			+ "           if (collapseATo == -1 && clickedItem.getName() < (collapsedA.length-1)){\n"
			+ "               heightsA.push([classesA.indexOf(collapsedA[clickedItem.getName()]),classesA.length]);\n"
			+ "               collapsedA.splice(clickedItem.getName()+1);\n"
			+ "               collapsedAlevels.splice(clickedItem.getName()+1);\n"
			+ "               clickedA.push(collapsedA[clickedItem.getName()]);\n"
			+ "           }\n"
			+ "       } else {\n"
			+ "       //recover extracted names and levels\n"
			+ "           var expandAFrom = classesA.indexOf(collapsedA[clickedItem.getName()]);\n"
			+ "           var prevLevel = collapsedAlevels[clickedItem.getName()];\n"
			+ "           var expandATo = classesA.indexOf(collapsedA[clickedItem.getName()+1]);\n"
			+ "           if (expandATo == -1){\n"
			+ "               collapsedA = collapsedA.concat(classesA.slice(expandAFrom+1));\n"
			+ "               collapsedAlevels = collapsedAlevels.concat(levelsA.slice(expandAFrom+1));\n"
			+ "               clickedA.splice(0,clickedA.length);\n"
			+ "               heightsA.splice(0,heightsA.length);\n"
			+ "           } else {\n"
			+ "               var tail = collapsedA.slice(clickedItem.getName()+1);\n"
			+ "               var head = collapsedA.slice(0,clickedItem.getName()+1);\n"
			+ "               collapsedA = head.concat(classesA.slice(expandAFrom+1,expandATo),tail);\n"
			+ "               head = collapsedAlevels.slice(0,clickedItem.getName()+1);\n"
			+ "               tail = collapsedAlevels.slice(clickedItem.getName()+1);\n"
			+ "               collapsedAlevels = head.concat(levelsA.slice(expandAFrom+1,expandATo),tail);\n"
			+ "               clickedA.splice(isClicked,1);\n"
			+ "               heightsA.splice(isClicked,1);\n"
			+ "           }\n"
			+ "       }\n"
			+ "   lineas.removeChildren();\n"
			+ "   stage.reset();\n"
			+ "   dibujo(stage);\n"
			+ "   }\n"
			+ "   if (modo == 1){\n"
			+ "       if (collection == 0)\n"
			+ "           sessionStorage.newpairA = clickedItem.getName();\n"
			+ "       if (collection == 1)\n"
			+ "           sessionStorage.newpairA = clickedItem.getName()+classIDsA.length;\n"
			+ "       if (collection == 2)\n"
			+ "           sessionStorage.newpairA = clickedItem.getName()+classIDsA.length+propertiesA.length;\n"
			+ "       if (sessionStorage.newpairB.length == 0){\n"
			+ "           escribe(mensaje, clickedItem.getText()+\" has been selected, select the right class.\", 10, 25);\n"
			+ "       } else {\n"
			+ "           clickActionFinisher();\n"
			+ "       }"
			+ "   }\n"
			+ "};\n"
			+ "function clickActionB(clickedItem,collection){\n"
			+ "   if (modo == 0){\n"
			+ "       var isClicked = clickedB.indexOf(collapsedB[clickedItem.getName()]);\n"
			+ "       if (isClicked == -1){\n"
			+ "           var prevLevel = collapsedBlevels[clickedItem.getName()];\n"
			+ "           var collapseBTo = collapsedBlevels.slice(clickedItem.getName()+1).indexOf(prevLevel);\n"
			+ "           var collapseBTo2 = collapsedBlevels.slice(clickedItem.getName()+1).indexOf(prevLevel-1);\n"
			+ "           if (collapseBTo2 >= 0 &&"
			+ "              (collapseBTo == -1 || collapseBTo2 < collapseBTo)){\n"
			+ "               collapseBTo = collapseBTo2;\n"
			+ "           }\n"
			+ "           if (collapseBTo > 0 &&\n"
			+ "               collapsedBlevels[(clickedItem.getName()+collapseBTo-1)] >= prevLevel){\n"
			+ "			      collapsedB.splice(clickedItem.getName()+1,collapseBTo);\n"
			+ "               heightsB.push([classesB.indexOf(collapsedB[clickedItem.getName()]),collapseBTo]);\n"
			+ "               collapsedBlevels.splice(clickedItem.getName()+1,collapseBTo);\n"
			+ "               clickedB.push(collapsedB[clickedItem.getName()]);\n"
			+ "           } else if (collapseBTo == -1 && clickedItem.getName() < (collapsedB.length-1)){\n"
			+ "               heightsB.push([classesB.indexOf(collapsedB[clickedItem.getName()]),classesB.length]);\n"
			+ "               collapsedB.splice(clickedItem.getName()+1);\n"
			+ "               collapsedBlevels.splice(clickedItem.getName()+1);\n"
			+ "               clickedB.push(collapsedB[clickedItem.getName()]);\n"
			+ "           }\n"
			+ "       } else {\n"
			+ "           //recover extracted names and levels\n"
			+ "           var expandBFrom = classesB.indexOf(collapsedB[clickedItem.getName()]);\n"
			+ "           var prevLevel = collapsedBlevels[clickedItem.getName()];\n"
			+ "           var expandBTo = classesB.indexOf(collapsedB[clickedItem.getName()+1]);\n"
			+ "           if (expandBTo == -1){\n"
			+ "               collapsedB = collapsedB.concat(classesB.slice(expandBFrom+1));\n"
			+ "               collapsedBlevels = collapsedBlevels.concat(levelsB.slice(expandBFrom+1));\n"
			+ "               clickedB.splice(0,clickedB.length);\n"
			+ "               heightsB.splice(0,heightsB.length);\n"
			+ "           } else {\n"
			+ "               var tail = collapsedB.slice(clickedItem.getName()+1);\n"
			+ "               var head = collapsedB.slice(0,clickedItem.getName()+1);\n"
			+ "               collapsedB = head.concat(classesB.slice(expandBFrom+1,expandBTo),tail);\n"
			+ "               head = collapsedBlevels.slice(0,clickedItem.getName()+1);\n"
			+ "               tail = collapsedBlevels.slice(clickedItem.getName()+1);\n"
			+ "               collapsedBlevels = head.concat(levelsB.slice(expandBFrom+1,expandBTo),tail);\n"
			+ "               clickedB.splice(isClicked,1);\n"
			+ "               heightsB.splice(isClicked,1);\n"
			+ "           }\n"
			+ "       }\n"
			+ "       lineas.removeChildren();\n"
			+ "       stage.reset();\n"
		    + "       dibujo(stage);\n"
			+ "   }\n"
			+ "   if (modo == 1){\n"
			+ "       if (collection == 0)\n"
			+ "           sessionStorage.newpairB = clickedItem.getName();\n"
			+ "       if (collection == 1)\n"
			+ "           sessionStorage.newpairB = clickedItem.getName()+classIDsB.length;\n"
			+ "       if (collection == 2)\n"
			+ "           sessionStorage.newpairB = clickedItem.getName()+classIDsB.length+propertiesB.length;\n"
			+ "       if (sessionStorage.newpairA.length == 0){\n"
			+ "           escribe(mensaje, clickedItem.getText()+\" has been selected, select the left class.\", 10, 25);\n"
			+ "       } else {\n"
			+ "           clickActionFinisher();\n"
			+ "       }\n"
			+ "   }\n"
			+ "};\n"
			+ "function dibujo(stage){\n"
			+ "    var marks = new Kinetic.Layer();\n"
			+ "    var nodesA = new Kinetic.Layer();\n"
			+ "    var nodesB = new Kinetic.Layer();\n"
			+ "    var tiplayer = new Kinetic.Layer();\n"
			+ "    var bg = new Kinetic.Rect({\n"
			+ "         x: 0,\n"
			+ "         y: 0,\n"
			+ "         width: 0,\n"
			+ "         height: 15,\n"
			+ "         fill: 'white',\n"
			+ "         stroke: 'black',\n"
			+ "         strokeWidth: 1,\n"
			+ "         visible: false\n"
			+ "         });\n"
			+ "    tiplayer.add(bg);\n"
			+ "    lineas.removeChildren();\n"
			+ "for (var n=0;n<(collapsedA.length-offsetA)-1;n++){\n"
			+ "     var nodo = new Kinetic.Text({\n"
			+ "         x: collapsedAlevels[n+offsetA]*30+40,\n"
			+ "         y: n*30+40,\n"
			+ "         text: collapsedA[n+offsetA],\n"
			+ "         name: n+offsetA,\n"
			+ "         fontSize: 16,\n"
			+ "         fontFamily: 'Verdana',\n"
			+ "         fill: 'black',\n"
			+ "         fontStyle: 'normal'\n"
			+ "     });\n"
			+ "    if (nodo.getText() == '$'){\n"
	        + "    nodo.setText(classIDsA[nodo.getName()]);\n"
	        + "    }\n"
			+ "     var mark = new Kinetic.RegularPolygon({\n"
			+ "         x: 32,\n"
			+ "         y: n*30+45,\n"
			+ "         name: n+offsetA,\n"
			+ "         sides: 3,\n"
			+ "         radius: 8,\n"
			+ "         rotationDeg : 60,\n"
			+ "         fill: 'black'\n"
			+ "     });\n"
			+ "var isClicked = clickedA.indexOf(nodo.getText());\n"
			+ "    if (isClicked != -1){\n"
			+ "    mark.setRotationDeg(90);\n"
			+ "    }\n"
			+ "    mark.on('mouseover', function(){\n"
			+ "            this.setFill(\"red\");\n"
			+ "            marks.draw();\n"
			+ "    });\n"
			+ "    mark.on('mouseout', function(){\n"
			+ "            this.setFill(\"black\");\n"
			+ "            marks.draw();\n"
			+ "    });\n"
			+ "    mark.on('click', function(){"
			+ "            clickActionA(this,0);\n"
			+ "    });\n"
			+ "    nodo.on('mousemove', function(){\n"
			+ "            var mousePos = stage.getMousePosition();\n"
			+ "            tooltip(tiplayer, bg, onto1+\"#\"+classIDsA[classesA.indexOf(collapsedA[this.getName()])],\n"
			+ "                    mousePos.x, mousePos.y);\n"
			+ "            this.setFill(\"red\");\n"
			+ "            nodesA.draw();\n"
			+ "    });\n"
			+ "    nodo.on('mouseout', function(){\n"
			+ "            this.setFill(\"black\");\n"
			+ "            bg.setVisible(false);\n"
			+ "            bg.setWidth(0);\n"
			+ "            bg.setX(0);\n"
			+ "            bg.setY(0);\n"
			+ "            tiplayer.clear();\n"
			+ "            nodesA.draw();\n"
			+ "    });\n"
			+ "    nodo.on('click', function(){\n"
			+ "            clickActionA(this,0);\n"
			+ "    });\n"
			+ "    var isCollapsable = checkMarkA(n+offsetA);\n"
			+ "    if (modo == 0 && (isClicked != -1 || isCollapsable == 0)){\n"
			+ "    marks.add(mark);\n"
			+ "    }\n"
			+ "    nodesA.add(nodo);\n"
			+ "}\n"
			+ "var j = 0;\n"
			+ "var k = 0;\n"
			+ "if (document.getElementById(\"propchk\").checked){\n"
			+ "while (k>=0 && (k+n < nottoofar)\n"
			+ "   && (k < (propertiesA.length-offsetPA))){\n" 
			+ "    var nodo = new Kinetic.Text({\n" 
			+ "         x: 40,\n"
			+ "         y: (k+n)*30+40,\n"
			+ "         text: propertyLabelsA[k+offsetPA],\n"
			+ "         name: k+offsetPA,\n"
			+ "         fontSize: 16,\n"
			+ "         fontFamily: 'Verdana',\n"
            + "         fill: 'black',\n"
			+ "         fontStyle: 'normal'\n"
            + "    });\n"
			+ "    nodo.on('mousemove', function(){\n"
            + "            var mousePos = stage.getMousePosition();\n"
			+ "            tooltip(tiplayer, bg,\n"
            + "                    onto1+\"#\"+propertiesA[this.getName()],\n"
			+ "                    mousePos.x, mousePos.y);\n"
            + "            this.setFill(\"red\");\n"
		    + "            nodesA.draw();\n"
			+ "    });\n" 
		    + "    nodo.on('mouseout', function(){\n"
			+ "            this.setFill(\"black\");\n"
		    + "            bg.setVisible(false);\n"
			+ "            bg.setWidth(0);\n"
		    + "            bg.setX(0);\n"
			+ "            bg.setY(0);\n"
            + "            tiplayer.clear();\n"
			+ "            nodesA.draw();\n"
			+ "    });\n"
			+ "    nodo.on('click', function(){"
			+ "            clickActionA(this,1);"
			+ "    });\n"
			+ "nodesA.add(nodo);\n"
            + "k++;\n"
			+ "}\n"
            + "}\n"
			+ "if (document.getElementById(\"datachk\").checked){\n"
			+ "while (j>=0 && (j+k+n < nottoofar)\n"
			+ "   && (j < (datatypesA.length-offsetDA))){\n"
			+ "var nodo = new Kinetic.Text({\n"
			+ "         x: 40,\n"
			+ "         y: (j+k+n)*30+40,\n"
			+ "         text: datatypeLabelsA[j+offsetDA],\n"
			+ "         name: j+offsetDA,\n"
			+ "         fontSize: 16,\n"
			+ "         fontFamily: 'Verdana',\n"
			+ "         fill: 'black',\n"
			+ "         fontStyle: 'normal'\n"
			+ "    });\n"
			+ "    nodo.on('mousemove', function(){\n"
			+ "            var mousePos = stage.getMousePosition();\n"
			+ "            tooltip(tiplayer, bg,\n"
			+ "                    onto1+\"#\"+datatypesA[this.getName()],\n"
			+ "                    mousePos.x, mousePos.y);\n"
			+ "            this.setFill(\"red\");\n"
			+ "            nodesA.draw();\n"
			+ "    });\n"
			+ "    nodo.on('mouseout', function(){\n"
			+ "            this.setFill(\"black\");\n"
			+ "            bg.setVisible(false);\n"
			+ "            bg.setWidth(0);\n"
			+ "            bg.setX(0);\n"
			+ "            bg.setY(0);\n"
			+ "            tiplayer.clear();\n"
			+ "            nodesA.draw();\n"
			+ "    });\n"
			+ "    nodo.on('click', function(){\n"
			+ "            clickActionA(this,2);\n"
			+ "    });\n"
			+ "nodesA.add(nodo);\n"
			+ "j++;\n"
			+ "}\n"
			+ "}\n";
	
	public static final String tree2 = 
			
			"for (n=0;n<(collapsedB.length-offsetB)-1;n++){\n"
	        + "     var nodo = new Kinetic.Text({\n"
			+ "         x: collapsedBlevels[n+offsetB]*30+640,\n"
			+ "         y: n*30+40,\n"
			+ "         text: collapsedB[n+offsetB],\n"
			+ "         name: n+offsetB,\n"
			+ "         fontSize: 16,\n"
			+ "         fontFamily: 'Verdana',\n"
			+ "         fill: 'black'\n"
			+ "    });\n"
			+ "    if (nodo.getText() == '$'){\n"
	        + "    nodo.setText(classIDsB[nodo.getName()]);\n"
	        + "    }\n"
			+ "     var mark = new Kinetic.RegularPolygon({\n"
			+ "         x: 632,\n"
			+ "         y: n*30+45,\n"
			+ "         name: n+offsetB,\n"
			+ "        sides: 3,\n"
			+ "        radius: 8,\n"
			+ "        rotationDeg : 60,\n"
			+ "        fill: 'black'\n"
			+ "      });\n"
			+ "var isClicked = clickedB.indexOf(nodo.getText());\n"
			+ "    if (isClicked != -1){\n"
			+ "    mark.setRotationDeg(90);\n"
			+ "    }\n"
			+ "    mark.on('mouseover', function(){\n"
			+ "            this.setFill(\"red\");\n"
			+ "            marks.draw();\n"
			+ "    });\n"
			+ "    mark.on('mouseout', function(){\n"
			+ "            this.setFill(\"black\");\n"
			+ "            marks.draw();\n"
			+ "    });\n"
			+ "    mark.on('click', function(){\n"
			+ "            clickActionB(this,0);\n"
			+ "    });\n"
			+ "    nodo.on('mousemove', function(){\n"
			+ "            var mousePos = stage.getMousePosition();\n"
			+ "            tooltip(tiplayer, bg, onto2+\"#\"+classIDsB[classesB.indexOf(collapsedB[this.getName()])],\n"
			+ "                    mousePos.x, mousePos.y);\n"
			+ "            this.setFill(\"red\");\n"
			+ "            nodesB.draw();\n"
			+ "    });\n"
			+ "    nodo.on('mouseout', function(){\n"
			+ "            bg.setVisible(false);\n"
			+ "            bg.setWidth(0);\n"
			+ "            bg.setX(0);\n"
			+ "            bg.setY(0);\n"
			+ "            tiplayer.clear();\n"
			+ "            this.setFill(\"black\");\n"
			+ "            nodesB.draw();\n"
			+ "    });\n"
			+ "    nodo.on('click', function(){\n"
			+ "            clickActionB(this,0);\n"
			+ "    });\n"
			+ "    var isCollapsable = checkMarkB(n+offsetB);"
			+ "    if (modo == 0 && (isClicked != -1 || isCollapsable == 0)){\n"
			+ "    marks.add(mark);\n"
			+ "    }\n"
			+ "    nodesB.add(nodo);\n"
			+ "}\n"
			+ "j = 0;\n"
			+ "k = 0;\n"
			+ "if (document.getElementById(\"propchk\").checked){\n"
            + "while (k>=0 && (k+n < nottoofar)\n"
			+ "   && (k < (propertiesB.length-offsetPB))){\n"
			+ "    var nodo = new Kinetic.Text({\n"
			+ "        x: 640,\n"
			+ "        y: (k+n)*30+40,\n"
			+ "        text: propertyLabelsB[k+offsetPB],\n"
			+ "        name: k+offsetPB,\n"
			+ "        fontSize: 16,\n"
			+ "        fontFamily: 'Verdana',\n"
			+ "        fill: 'black',\n"
			+ "        fontStyle: 'normal'\n"
			+ "    });\n"
			+ "    nodo.on('mousemove', function(){\n"
			+ "            var mousePos = stage.getMousePosition();\n"
			+ "            tooltip(tiplayer, bg,\n"
			+ "                    onto2+\"#\"+propertiesB[this.getName()],\n"
			+ "                    mousePos.x, mousePos.y);\n"
			+ "            this.setFill(\"red\");\n"
			+ "            nodesB.draw();\n"
			+ "    });\n"
			+ "    nodo.on('mouseout', function(){\n"
			+ "            this.setFill(\"black\");\n"
			+ "            bg.setVisible(false);\n"
			+ "            bg.setWidth(0);\n"
			+ "            bg.setX(0);\n"
			+ "            bg.setY(0);\n"
			+ "            tiplayer.clear();\n"
			+ "            nodesB.draw();\n"
			+ "    });\n"
			+ "    nodo.on('click', function(){\n"
			+ "            clickActionB(this,0);\n"
			+ "    });\n"
			+ "    nodesB.add(nodo);\n"
			+ "k++;\n"
			+ "}\n"
			+ "}\n"
			+ "if (document.getElementById(\"datachk\").checked){\n"
			+ "while (j>=0 && (j+k+n < nottoofar)\n"
			+ "   && (j < (datatypesB.length-offsetDB))){\n"
			+ "var nodo = new Kinetic.Text({\n"
			+ "         x: 640,\n"
			+ "         y: (j+k+n)*30+40,\n"
			+ "         text: datatypeLabelsB[j+offsetDB],\n"
			+ "         name: j+offsetDB,\n"
			+ "         fontSize: 16,\n"
			+ "         fontFamily: 'Verdana',\n"
			+ "         fill: 'black',\n"
			+ "         fontStyle: 'normal'\n"
			+ "    });\n"
			+ "    nodo.on('mousemove', function(){\n"
			+ "            var mousePos = stage.getMousePosition();\n"
			+ "            tooltip(tiplayer, bg,\n"
			+ "                    onto2+\"#\"+datatypesB[this.getName()],\n"
			+ "                    mousePos.x, mousePos.y);\n"
			+ "            this.setFill(\"red\");\n"
			+ "            nodesB.draw();\n"
			+ "    });\n"
			+ "    nodo.on('mouseout', function(){\n"
			+ "            this.setFill(\"black\");\n"
			+ "            bg.setVisible(false);\n"
			+ "            bg.setWidth(0);\n"
			+ "            bg.setX(0);\n"
			+ "            bg.setY(0);\n"
			+ "            tiplayer.clear();\n"
			+ "            nodesB.draw();\n"
			+ "    });\n"
			+ "    nodo.on('click', function(){\n"
			+ "            clickActionB(this,2);\n"
			+ "    });\n"
			+ "nodesB.add(nodo);\n"
			+ "j++;\n"
			+ "}\n"
			+ "}\n";
	
	public static final String tree3 =
			//"0];\n" +
	        "for (n=0;n<(uniones.length-1);n++){\n" +
			"    if (((uniones[n][0] != \">\"\n" +
			"      && uniones[n][0] != \"<\"\n" +
			"      && uniones[n][0] != \"=\") && (document.getElementById(\"others\").checked))\n" +
			"      || (uniones[n][0] == \">\" && document.getElementById(\">\").checked)\n" +
			"      || (uniones[n][0] == \"<\" && document.getElementById(\"<\").checked)\n" +
			"      || (uniones[n][0] == \"=\" && document.getElementById(\"=\").checked)\n" +
			"    ){\n" +
			"     var positionA = checkA(uniones[n][2]);\n" +
			"     var positionB = checkB(uniones[n][3]);\n" +
			"     if (positionA != -1 && positionB != -1 && uniones[n][1] >= umbral){\n" +
	        //"         var k = n;" +
			"         var pointArr;\n"
			//+ "         if (positionA > positionB){\n"
			+ "       pointArr = [350, (45+(positionA*30)),\n" +
			  "                   620, (45+(positionB*30)),\n" +
			  "                   620, (50+(positionB*30)),\n" +
			  "                   350, (50+(positionA*30))];\n"
			//+ "         } else {"
			//+ "            pointArr = [280, (45+(positionA*30)), 400, (45+(positionA*30)), 400, (45+(positionB*30)), 520, (45+(positionB*30)), 520, (50+(positionB*30)), 395, (50+(positionB*30)), 395, (50+(positionA*30)), 280, (50+(positionA*30))];\n"
			//+ "         }\n"
			+
	        "         var valor = new Kinetic.Text({\n" +
	        //"         x: uniones[n][2][4],\n" +
	        "         x: 485,\n" +
	        //"         y: (uniones[n][2][5] - 15),\n" +
	        //"         y: (30*(positionB) + 30),\n" +
	        "         y: (15*(positionA+positionB) + 30),\n" +
	        "         text: uniones[n][0]+\" \"+uniones[n][1],\n" +
	        "         name: positionA+\"@\"+positionB," +
	        "         fontSize: 16,\n" +
	        "         fontFamily: 'Verdana',\n" +
	        "         fill: 'black'\n" +
	        "         });\n" +
	        "         lineas.add(valor);\n" +
	        //"         var union = new Kinetic.Polygon({\n" +
	        "         var union = new Kinetic.Polygon({\n" +
	        //"         points: uniones[n][2],\n" +
	        //"         points: [280, (45+(uniones[n][2]*30)), 400, (45+(uniones[n][2]*30)), 400, (45+(uniones[n][3]*30)), 520, (45+(uniones[n][3]*30)), 520, (50+(uniones[n][3]*30)), 395, (50+(uniones[n][3]*30)), 395, (50+(uniones[n][2]*30)), 280, (50+(uniones[n][2]*30))],\n" +
	        "         points: pointArr,\n" +
	        "         fill: 'black',\n" +
	        "         name: n,\n" +
	        "         id: positionA+\"@\"+positionB," +
	        "         lineCap: 'round',\n" +
	        "         lineJoin: 'round'\n" +
	        "         });\n" +
	        "         union.on('mouseover', function(){\n" +
			"         this.setFill(\"red\");\n" +
			"         lineas.draw();\n" +
			"         });\n" +
			"         union.on('mouseout', function(){\n" +
			"         this.setFill(\"black\");\n" +
			"         lineas.draw();\n" +
			"         });\n" +
			"         union.on('click', function(){\n" +
			"            if (modo == 1){\n" +
			"            if (document.getElementById(\"rd=\").checked){\n" + 
			"            uniones[this.getName()][0] = \"=\";\n" +
			"            }\n" +
			"            if (document.getElementById(\"rd<\").checked){\n" + 
			"            uniones[this.getName()][0] = \"<\";\n" +
			"            }\n" +
			"            if (document.getElementById(\"rd>\").checked){\n" + 
			"            uniones[this.getName()][0] = \">\";\n" +
			"            }\n" +
			"            uniones[this.getName()][1] = parseFloat(document.getElementById(\"valorin\").value);\n"+
			"            var valor = lineas.get('.'+this.getId());\n" +
			"            valor[0].setText(uniones[this.getName()][0]+\" \"+uniones[this.getName()][1]);\n" +
			"            stage.reset();\n" +
			"            dibujo(stage);\n" +
			//"            escribe(mensaje, uniones[this.getName()][0]+uniones[this.getName()][1]+\" en la posicion \"+this.getName(), 10, 25);\n" +
			"            }\n" +
			"            });\n" +
	        "     lineas.add(union);\n" +
	        "     }\n" +
	        "     }\n" +
	        "}\n";
	
	public static String treetail =
			"stage.add(mensaje);\n" +
			"stage.add(marks);\n"+
			"stage.add(nodesA);\n"+
			"stage.add(nodesB);\n"+
	        "stage.add(lineas);\n"+
	        "stage.add(tiplayer);\n" +
			"};\n" +
	        "inicializar();\n" +
			"dibujo(stage);\n" +
			"</script>\n" +
			"</body>\n" +
			"</html>\n";
}
